[package]
name = "oma-id-agent-store"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = "2"
hex = "0.4"
oma-id-agent-core = { path = "../oma-id-agent-core" }
serde.workspace = true
serde_json.workspace = true
thiserror = "2"

[dev-dependencies]
tempfile = "3"

[lib]
path = "src/lib.rs"
