#!/bin/bash
# Provision OMA-ID management into a TARGET system root (plan §7.2 step 6:
# "install the trusted packages and stage only the minimal key-bound
# activation state"). Runs in the live install environment AFTER the omarchy
# install has written its own /etc/pam.d, so our wiring is never overwritten.
#
# Usage: oma-id-provision-target.sh <target-root> [server-url] [device-id]
# Gated: the installer choice file must say work-school (ADR-006); personal
# and work-school-personal installs get NOTHING.
#
# What is staged:
#   <root>/usr/bin/oma-id-agent          the pinned agent binary (from the ISO)
#   <root>/usr/lib/security/pam_oma_id.so
#   <root>/usr/lib/systemd/system/oma-id-agent.service  (enabled)
#   <root>/etc/oma-id-agent.json         the §6.2-validated server URL
#   <root>/etc/pam.d/{sddm,omarchy-lock-*} wired to pam_oma_id (§8.2)
#
# The device key is NOT staged (§7.2 step 6: never into a reusable image
# baseline) — the agent generates it on first boot of the installed system
# and self-enrolls; an administrator accepts the request in the review UI.
set -euo pipefail

root="${1:?usage: oma-id-provision-target.sh <target-root> [server-url] [device-id]}"

# Self-reporting: everything this script does lands BOTH in the live install
# log and in a log INSIDE the target root, so the INSTALLED system can show
# exactly what happened after the live environment is gone.
install -d -m 0755 "$root/var/log"
exec > >(tee -a /var/log/omarchy-install.log "$root/var/log/oma-id-provision-install.log" >/dev/null) 2>&1 || true
server_url="${2:-}"
device_id="${3:-workstation-1}"
choice_file=/run/oma-id/standin-choice.json

# --- gate (§6.4 / ADR-006): only an explicit work-school choice provisions ---
# The /run copy is tmpfs and can vanish (mid-install reboot/cleanup); the
# target-root backup made by the install script survives on disk.
if [[ ! -f "$choice_file" && -f "$root/etc/oma-id/standin-choice.json" ]]; then
  choice_file="$root/etc/oma-id/standin-choice.json"
  echo "oma-id-provision-target: using the target-root choice backup ($choice_file)" >&2
fi
if [[ -f "$choice_file" ]]; then
  mode=$(jq -r '.mode // empty' "$choice_file")
else
  mode=""
fi
if [[ "$mode" != "work-school" ]]; then
  echo "oma-id-provision-target: choice mode '${mode:-none}' — no OMA-ID management staged (personal install)."
  # Record WHY (this output lands in the installed system's log): was the
  # file gone (tmpfs/reboot), or there but unreadable (jq)?
  if [[ -f "$choice_file" ]]; then
    echo "oma-id-provision-target: choice file EXISTS at $choice_file; content:"
    head -c 300 "$choice_file" | sed 's/^/  /'
  else
    echo "oma-id-provision-target: choice file MISSING at $choice_file"
    ls -la /run/oma-id 2>&1 | sed 's/^/  /' || true
  fi
  exit 0
fi

# The server URL and device name come from the §6.2-validated choice
# (STEP 0 names the machine) unless given explicitly.
if [[ -z "$server_url" ]]; then
  server_url=$(jq -r '.server // empty' "$choice_file")
fi
if [[ -z "$server_url" ]]; then
  echo "oma-id-provision-target: no validated server URL in the choice file" >&2
  exit 1
fi
if [[ -z "$device_id" || "$device_id" == "workstation-1" ]]; then
  chosen=$(jq -r '.device // empty' "$choice_file")
  [[ -n "$chosen" ]] && device_id="$chosen"
fi

# The live environment already has the pinned artifacts at their system
# paths (installed by the ISO layer) — one source of truth.
agent_src=/usr/bin/oma-id-agent
module_src=/usr/lib/security/pam_oma_id.so
unit_src=/usr/lib/systemd/system/oma-id-agent.service
[[ -x "$agent_src" ]] || { echo "oma-id-provision-target: missing $agent_src" >&2; exit 1; }
[[ -f "$module_src" ]] || { echo "oma-id-provision-target: missing $module_src" >&2; exit 1; }
[[ -f "$unit_src" ]] || { echo "oma-id-provision-target: missing $unit_src" >&2; exit 1; }

install -D -m 0755 "$agent_src" "$root/usr/bin/oma-id-agent"
install -D -m 0644 "$module_src" "$root/usr/lib/security/pam_oma_id.so"
install -D -m 0644 "$unit_src" "$root/usr/lib/systemd/system/oma-id-agent.service"

# The device identity (docs/p0/installer-enrollment.md §7.2 step 6): the seed
# generated by STEP 0's keygen_and_enroll — staged ONLY here, inside the
# LUKS-protected target. Loaded by the agent on first boot; the server
# already holds the matching public key from the reservation. Missing at
# staging = the reservation flow never ran = fail the stage loudly.
key_src=/run/oma-id-install/device.key
# quattro: the orchestrator phase stages the seed directly into the target
# before calling us — accept that pre-staged copy too.
if [[ ! -s "$key_src" && -s "$root/var/lib/oma-id/device.key" ]]; then
  key_src="$root/var/lib/oma-id/device.key"
fi
if [[ ! -s "$key_src" ]]; then
  echo "oma-id-provision-target: no device key in /run/oma-id-install or $root/var/lib/oma-id — refusing to stage (unmanaged)" >&2
  exit 1
fi
install -D -m 0600 "$key_src" "$root/var/lib/oma-id/device.key"
echo "oma-id-provision-target: staged device key (pubkey registered at enrollment)"

# Config: the §6.2-validated server URL (device_id is the agent's PROPOSED
# id — the administrator sees and can rename it at acceptance). State lives
# in /var/lib/oma-id (persistent on the installed system).
install -d -m 0755 "$root/etc"
cat >"$root/etc/oma-id-agent.json" <<EOF
{
  "server_url": "$server_url",
  "device_id": "$device_id",
  "state_dir": "/var/lib/oma-id",
  "socket_path": "/run/oma-id/agent.sock",
  "check_in_interval_seconds": 300
}
EOF
chmod 0644 "$root/etc/oma-id-agent.json"

# First-boot sequencing (§7.2 steps 7-8): the DAEMON is NOT enabled yet —
# it must not check in before the bootstrap consumes the reservation and
# sets the person's local credential (an early daemon check-in would burn
# the one-time bootstrap). oma-id-first-boot.service (enabled) retries the
# bootstrap until the admin accepts, then enables + starts the daemon.
install -d -m 0755 "$root/usr/libexec/oma-id"
cat >"$root/usr/libexec/oma-id/first-boot.sh" <<'SCRIPT'
#!/bin/bash
# Reserve-then-activate first boot (docs/p0/installer-enrollment.md): retry
# the bootstrap until the reservation is accepted, provision the account +
# set the one-time bootstrap password, then enable + start the daemon.
set -euo pipefail
MARKER=/var/lib/oma-id/.first-boot-done
exec >>/var/log/oma-id-first-boot.log 2>&1
echo "[$(date -u +%FT%TZ)] oma-id first boot: begin"
if [[ -f "$MARKER" ]]; then
  echo "[$(date -u +%FT%TZ)] already bootstrapped; exiting"
  exit 0
fi
/usr/bin/oma-id-agent bootstrap --config /etc/oma-id-agent.json
touch "$MARKER"
echo "[$(date -u +%FT%TZ)] oma-id bootstrap complete — enabling + starting daemon"
systemctl enable --now oma-id-agent.service
SCRIPT
chmod 0755 "$root/usr/libexec/oma-id/first-boot.sh"

install -d -m 0755 "$root/usr/lib/systemd/system"
cat >"$root/usr/lib/systemd/system/oma-id-first-boot.service" <<UNIT
[Unit]
Description=OMA-ID first-boot reserve-then-activate
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/libexec/oma-id/first-boot.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
UNIT

install -d -m 0755 "$root/etc/systemd/system/multi-user.target.wants"
ln -sfn /usr/lib/systemd/system/oma-id-first-boot.service \
  "$root/etc/systemd/system/multi-user.target.wants/oma-id-first-boot.service"

# §8.2 PAM wiring: auth + account through pam_oma_id. The same wiring the
# live ISO layer applies, applied to the target AFTER the omarchy install.
# §8.2 PAM wiring: insert pam_oma_id as SUFFICIENT before the stack's
# pam_unix line — managed accounts authenticate through the agent (lease +
# local credential), local/rescue accounts fall through to local auth.
# Appending at the stack's end is WRONG on quattro: omarchy-apply-lock ends
# the auth section with `auth [default=die] pam_faillock.so authsucc`, so
# appended lines are unreachable (and the lock would deny everything).
for service in sddm omarchy-lock-password omarchy-lock-fingerprint; do
  pam="$root/etc/pam.d/$service"
  if [[ ! -f "$pam" ]]; then
    install -d -m 0755 "$root/etc/pam.d"
    printf '# OMA-ID managed login (created by oma-id-provision-target)\nauth        sufficient   pam_oma_id.so\naccount     required     pam_oma_id.so\n' >"$pam"
  elif ! grep -q "pam_oma_id.so" "$pam"; then
    awk '
      /^[[:space:]]*-?auth[[:space:]].*pam_unix\.so/ && !inserted {
        print "auth        sufficient   pam_oma_id.so"
        print "account     required     pam_oma_id.so"
        inserted=1
      }
      { print }
    ' "$pam" > "$pam.oma-new" && mv "$pam.oma-new" "$pam"
    grep -q "pam_oma_id.so" "$pam" || printf '# OMA-ID managed login\nauth        sufficient   pam_oma_id.so\naccount     required     pam_oma_id.so\n' >>"$pam"
    echo "oma-id-provision-target: inserted pam_oma_id before pam_unix in $pam"
  fi
done

# The provisioned username (§8.4 mapping) for the orchestrator's login phase.
mapping_username=$(jq -r '.username // empty' "$root/var/lib/oma-id/posix-mapping.json" 2>/dev/null || true)
if [[ -z "$mapping_username" ]]; then
  mapping_username=$(getent passwd | awk -F: '$3 >= 10000 && $3 < 20000 {print $1; exit}' 2>/dev/null || true)
fi
printf '{"posix_username": "%s", "device_id": "%s"}\n' "$mapping_username" "$device_id" \
  > "$root/etc/oma-id/provision-output.json" 2>/dev/null || true
# The login phase (configure_oma_login) reads the provisioned username from here.
printf '%s\n' "$mapping_username" > "$root/etc/oma-id/login-username" 2>/dev/null || true

echo "oma-id-provision-target: staged agent+module+unit+config into $root (server: $server_url, proposed device: $device_id)"
echo "oma-id-provision-target: first boot will self-enroll; an administrator must accept the device."
