[package]
name = "oma-id-agent"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = "2"
hex = "0.4"
libc.workspace = true
oma-id-agent-core = { path = "../oma-id-agent-core" }
oma-id-agent-daemon = { path = "../oma-id-agent-daemon" }
oma-id-agent-ipc = { path = "../oma-id-agent-ipc" }
oma-id-agent-store = { path = "../oma-id-agent-store" }
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
ureq = { version = "2", default-features = false, features = ["tls", "json"] }
thiserror = "2"

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "oma-id-agent"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
